name: Update Data
on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Run update script
        run: |
          node updateData.js

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add update.txt
          git commit -m 'Updated update.txt with new timestamp'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
